spring:
  main:
    allow-bean-definition-overriding: 'true'
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todolist?createDatabaseIfNotExist=true
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
    repositories:
      enabled: true

server:
  port: 8080